version: '3.5'
name: sharding-repl-cache
services:
  # app server
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on: [mongos_router, redis_1]
    ports:
      - 8080:8080
    networks:
      app-network:
        ipv4_address: 173.17.0.5
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis_1:6379"

  # сервер конфигурации
  configSrv:
    image: mongo:latest # docker образ
    container_name: configSrv 
    restart: always
    ports:
      - 27017:27017
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - config-data:/Users/oleglistov/Documents/Yandex_architecture/Sprint_2/Task_2/sprint_2/mongo-sharding
    command:
      [
        "mongod",
        "--configsvr",  # запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27017" ]
      interval: 5s
      start_period: 10s

  # роутер
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - 27020:27020
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    volumes:
      - router-data:/data/db
    command:
      [
        "mongos", #обычная mongo в режиме роутера
        "--configdb", 
        "config_server/configSrv:27017", # передача данных сервера конфигурации
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27020" ]
      interval: 5s
      start_period: 10s

  # 1-й шард 
  shard1:
    image: mongo:latest
    container_name: shard1
    restart: always
    ports:
      - 27018:27018
    networks:
      app-network:
        ipv4_address: 173.17.0.9
    volumes:
      - shard1-data:/data/db
    command:
      [
        "mongod",
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "shard1",     # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s

  # 1-й шард реплика 1
  shard1_repl1:
    image: mongo:latest
    container_name: shard1_repl1
    restart: always
    ports:
      - 27022:27022
    networks:
      app-network:
        ipv4_address: 173.17.0.22
    volumes:
      - shard1-repl1-data:/data/db
    command:
      [
        "--replSet",
        "shard1",     # название реплики
        "--bind_ip_all",
        "--port",
        "27022"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27022" ]
      interval: 5s
      start_period: 10s    

  # 1-й шард реплика 2
  shard1_repl2:
    image: mongo:latest
    container_name: shard1_repl2
    restart: always
    ports:
      - 27023:27023
    networks:
      app-network:
        ipv4_address: 173.17.0.23
    volumes:
      - shard1-repl2-data:/data/db
    command:
      [
        "--replSet",
        "shard1",     # название реплики
        "--bind_ip_all",
        "--port",
        "27023"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27023" ]
      interval: 5s
      start_period: 10s

  # 2-й шард 
  shard2:
    image: mongo:latest
    container_name: shard2
    restart: always
    ports:
      - 27019:27019
    networks:
      app-network:
        ipv4_address: 173.17.0.8
    volumes:
      - shard2-data:/data/db
    command:
      [
        "mongod",
        "--shardsvr",  # запуск в режиме шардинга
        "--replSet",
        "shard2",      # название реплик
        "--bind_ip_all", # обратите внимание - она отличается от реплики 1-го шарда
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27019" ]
      interval: 5s
      start_period: 10s

  # 2-й шард replica 1
  shard2_repl1:
    image: mongo:latest
    container_name: shard2_repl1
    restart: always
    ports:
      - 27024:27024
    networks:
      app-network:
        ipv4_address: 173.17.0.24
    volumes:
      - shard2-repl1-data:/data/db
    command:
      [
        "--replSet",
        "shard2",      # название реплик
        "--bind_ip_all", # обратите внимание - она отличается от реплики 1-го шарда
        "--port",
        "27024"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27024" ]
      interval: 5s
      start_period: 10s

  # 2-й шард replica 2
  shard2_repl2:
    image: mongo:latest
    container_name: shard2_repl2
    restart: always
    ports:
      - 27025:27025
    networks:
      app-network:
        ipv4_address: 173.17.0.25
    volumes:
      - shard2-repl2-data:/data/db
    command:
      [
        "--replSet",
        "shard2",      # название реплик
        "--bind_ip_all", # обратите внимание - она отличается от реплики 1-го шарда
        "--port",
        "27025"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27025" ]
      interval: 5s
      start_period: 10s

  # cache
  redis_1:
    image: "redis:latest"
    container_name: redis_1
    ports:
      - "6379"
    volumes:
      - redis_1_data:/data
      - ./redis/redis.conf:/Users/oleglistov/Documents/Yandex_architecture/Sprint_2/Task_2/sprint_2/sharding-repl-cache/redis.conf
    command: [ "redis-server", "/Users/oleglistov/Documents/Yandex_architecture/Sprint_2/Task_2/sprint_2/sharding-repl-cache/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.12

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  config-data:
  router-data:
  shard1-data:
  shard2-data:
  redis_1_data:
  shard1-repl1-data:
  shard1-repl2-data:
  shard2-repl1-data:
  shard2-repl2-data:
